version: '3.8'

services:
  app:
    container_name: products-web-deploy-container
    image: products-web-deploy-image
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3001:3000'
