#!/bin/bash
# apply code style to the /src directory using prettier
# usage: ./cmd/format

# Abort script at first error
set -e

# Base dir
BASEDIR=$(dirname "$0")

# change to source directory
cd "$BASEDIR/.."

# Format code with prettier
npx prettier --write "src/**/*.{ts, tsx}"

# change back to the directory where the script has been called
cd -
